### ISSUE TITLE
Error on not empty dashboard

### ISSUE THREAD

**Issue by slobberbone** [NextDom/nextdom-core#1184]
Import a backup then try to display dashboard

```
 PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /usr/share/nextdom/src/Controller/Pages/DashBoardController.php:89
Stack trace:
#0 [internal function]: NextDom\Controller\Pages\DashBoardController::get(Array)
#1 /usr/share/nextdom/src/Helpers/PrepareView.php(375): call_user_func_array('NextDom\Control...', Array)
#2 /usr/share/nextdom/src/Helpers/PrepareView.php(427): NextDom\Helpers\PrepareView->getContentFromControllerRouteData(Object(Symfony\Component\Routing\Route), Array)
#3 /usr/share/nextdom/src/Helpers/Router.php(145): NextDom\Helpers\PrepareView->showContentByAjax()
#4 /usr/share/nextdom/src/Helpers/Router.php(93): NextDom\Helpers\Router->desktopView()
#5 /usr/share/nextdom/index.php(84): NextDom\Helpers\Router->show()
#6 {main}
```

**Comment by slobberbone** [comment]
Testé et validé 1/3

**Comment by slobberbone** [comment]
Testé et validé 1/3
