### ISSUE TITLE
Backup Samba - Erreur backup distant

### ISSUE THREAD

**Issue by GsCbo** [NextDom/nextdom-core#1261]
**Décrivez le bug**
Quand on effectue un backup samba. Le sauvegarde s'effectue mais l'archivage sur le serveur samba ne s'effectue pas avec l'erreur suivante.

`rotating backup archives...  OK
uploading backup to remote clouds... PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Icewind\SMB\TimeZoneProvider::__construct() must be an instance of Icewind\SMB\System, none given, called in /usr/share/nextdom/vendor/icewind/smb/src/ServerFactory.php on line 62 and defined in /usr/share/nextdom/plugins/sonos3/vendor/icewind/smb/src/TimeZoneProvider.php:30
Stack trace:
#0 /usr/share/nextdom/vendor/icewind/smb/src/ServerFactory.php(62): Icewind\SMB\TimeZoneProvider->__construct(Object(Icewind\SMB\System))
#1 /usr/share/nextdom/src/Helpers/Samba.php(45): Icewind\SMB\ServerFactory->__construct()
#2 /usr/share/nextdom/src/Helpers/Samba.php(71): NextDom\Helpers\Samba->__construct('IP', 'user', 'mdp', 'shareFolder')
#3 /usr/share/nextdom/src/Repo/RepoSamba.php(94): NextDom\Helpers\Samba::createFromConfig('backup')
#4 /usr/share/nextdom/src/Managers/BackupManager.php(395): NextDom\Repo\RepoSamba::backup_send('/var/lib/nextdo...')
#5 /usr/share/nextdom/src/Managers/BackupManager.php(104): NextDom\Managers\BackupManager::sendRemoteBack in /usr/share/nextdom/plugins/sonos3/vendor/icewind/smb/src/TimeZoneProvider.php on line 30`

**Comment reproduire ?**
Backup SMB bien paramétré et plugin sonos installé

**Screenshots**

**Information matérielles**
 - OS : [Debian 9.5]
 - Navigateur : [chrome]
 - Version NextDom : [depuis la 0.1.4 à la 0.3.0]
 - Branche NextDom : [master]

**Comment by Gis70** [comment]
Salut ça fonctionne chez moi, as tu bien remis ce qu'il fallait dans la config samba sous Nextdom car ça a évolué un peu. Peux tu poster ta config ?

**Comment by GsCbo** [comment]
![image](https://user-images.githubusercontent.com/44973640/62273525-09638580-b43e-11e9-9fa3-de31f1e58259.png)


Et je vois bien mes backups dispo dans la sauvegarde.

**Comment by vinceg77** [comment]
Je viens de lancer un backup. Chez moi je n'ai pas les mêmes erreurs dans 'avancement de la sauvegarde'. A la fin j'ai juste un problème de droits (mais en fait les backups sont quand même déposées dans le dossier samba configuré) :

rotating backup archives...  OK
uploading backup to remote clouds...
mkdir failed on directory /var/run/samba/msg.lock: Permission denied
mkdir failed on directory /var/run/samba/msg.lock: Permission denied
OK
*************** end of backup procedure at 2019-08-04 12:40:24 ***************
*************** elapsed time 97 ***************
*************** Closing with success ***************
[ / Create Backup Process ]

**Comment by Gis70** [comment]
Hello, il faut refaire la config SAMBA ce n'est pas bon. Supprimé tout, il y a l'exemple de ce qui doit être inscrit dans le champ.

Le message d'erreur est là mais ce n'est pas lui le problème, je l'ai aussi.

Voilà un exemple de config 
![image](https://user-images.githubusercontent.com/16589132/62430223-e674f200-b719-11e9-924d-f42572f689e3.png)

**Comment by vinceg77** [comment]
Oui j'ai l'équivalent et ca sauvegarde malgré les messages d'erreur

**Comment by Gis70** [comment]
et donc le transfert samba fonctionne aussi chez toi ?, le message d'erreur
c'est un bug dans le package de la fonction pas de nextdom

**Comment by vinceg77** [comment]
oui, malgré les messages d'erreur je retrouve bien au final une sauvegarde dans mon repertoire sur le serveur samba...

**Comment by GsCbo** [comment]
Perso si dans partage je mets pas //ip/dossier_partage ben dans la page Sauvegardes / Restaurations j'ai une erreur samba.

Mais ça résout pas mon soucis.

**Comment by Gis70** [comment]
tu es sur quelle version de Nextdom @GsCbo

**Comment by GsCbo** [comment]
la actuellement la 0.3.0, mais j'ai le soucis depuis que j'étais passé à la 0.1.4, puis j'ai l'impression au vu de mes logs que c'est un délire avec les dépendances installées par le plugin sonos

**Comment by Gis70** [comment]
J'avais pas vu effectivement il y a un conflit de dépendances peut être, par contre en 0.3.0 il faudra modifier ta config pour le partage... sinon cela ne marchera pas.

**Comment by GsCbo** [comment]
Ben si je modifie ma config c'est ce que je disais au dessus, c'est pas bon au niveau de la page Sauvegardes / Restaurations. Je vois plus mes backups Samba alors qu'avec celle ci ça fonctionne ^^

**Comment by Gis70** [comment]
c'est pas logique en 0.3.0 peut être encore à cause de sonos... tu pourrais essayer de le désinstaller ?

**Comment by GsCbo** [comment]
vais tester ce soir, toi il est installé chez toi?

**Comment by Gis70** [comment]
je n'ai pas sonos non, ça dit quoi alors ?

**Comment by GsCbo** [comment]
donc quand je le désinstalle les backups samba fonctionnent (j'ai tjrs un message d'erreur mais le backup se fait)
je le réinstalle et la les backups ne fonctionnent  plus.

@Gis70 tu pourrais tester chez toi stp vérifier que t'as le même comportement?

**Comment by slobberbone** [comment]
@GsCbo il y a un soucis lorsque le plugin Sonos est installé. Cependant en 0.4.X  sans le plugin, cela foncitonne. JE regarde comemnt corriger la compatibilité avec le plugin Sonos

**Comment by cyrilphoenix71** [comment]
@slobberbone s'en est ou ?
