### ISSUE TITLE
erreur restauration jeedom/nextdom

### ISSUE THREAD

**Issue by trarizakaria** [NextDom/nextdom-core#1442]
Jeedom v3.3.34   nextdom v 0.5.0 dev

```
[ Restore Backup Process ]
*************** starting restore procedure at 2019-10-26 21:30:17 ***************
...file used for restoration: /var/lib/nextdom/backup/backup-**********HOME-3.3.34-2019-10-26-00h49.tar.gz
OK
stopping Nextdom system......  OK
extracting backup archive......  OK
restoring plugins......  OK
restoring mysql database......  OK
importing Jeedom configuration......  OK
restoring custom data......  OK
migrating data...... ...Migration/Update process from --> 0.0.0
...Migration/Update process to --> 0.5.0
...Start migration process for migrate_0_0_0
ERROR 1060 (42S21) at line 36: Duplicate column name 'order'
ERROR 1060 (42S21) at line 37: Duplicate column name 'image'
ERROR 1060 (42S21) at line 38: Duplicate column name 'image'
ERROR 1060 (42S21) at line 39: Duplicate column name 'configuration'
ERROR 1060 (42S21) at line 40: Duplicate column name 'tags'
ERROR 1061 (42000) at line 42: Duplicate key name 'tags'
...Database basic update
...Done migration process for migrate_0_0_0
...Save migration process for migrate_0_0_0
...Start migration process for migrate_0_3_0
...Update theme folder
...Start moving files and folders process to /var/lib/nextdom
...Migrate adminer.php to data/custom/adminer.php
...Migrate CHANGELOG.md to data/custom/CHANGELOG.md
UnexpectedValueException: RecursiveDirectoryIterator::__construct(/var/lib/nextdom/data/custom/plans): failed to open dir: No such file or directory in /usr/share/nextdom/src/Helpers/MigrationHelper.php:298
Stack trace:
#0 /usr/share/nextdom/src/Helpers/MigrationHelper.php(298): RecursiveDirectoryIterator->__construct('/var/lib/nextdo...', 4096)
#1 /usr/share/nextdom/src/Helpers/MigrationHelper.php(193): NextDom\Helpers\MigrationHelper::movePersonalFoldersAndFilesToData('restore')
#2 /usr/share/nextdom/src/Helpers/MigrationHelper.php(102): NextDom\Helpers\MigrationHelper::migrate_0_3_0('restore')
#3 /usr/share/nextdom/src/Managers/BackupManager.php(470): NextDom\Helpers\MigrationHelper::migrate('restore')
#4 /usr/share/nextdom/install/restore.php(58): NextDom\Managers\BackupManager::restoreBackup('/var/lib/nextdo...')
#5 {main} Failure
>> *** ERROR ***
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/Utils.php on line 412
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/Utils.php on line 412
PHP Notice:  Array to string conversion in /usr/share/nextdom/src/Helpers/ConsoleHelper.php on line 100
>> *** TRACE *** Array
starting Nextdom system......  OK
*************** Closing with error ***************
[ / Restore Backup Process ]
```

**Comment by slobberbone** [comment]
Fixé en 0.5.1
