### ISSUE TITLE
Restore plante avec plugin Sonos

### ISSUE THREAD

**Issue by Astral0** [NextDom/nextdom-core#809]
On a ca dans les logs : 

```
Reinitialization dependencies : script...
Plugin restoration : sonos3...
PHP Fatal error:  Uncaught Error: Call to a member function getTags() on boolean in /var/www/nextdomdev/plugins/sonos3/vendor/duncan3dc/sonos/src/Network.php:265
Stack trace:
#0 /var/www/nextdomdev/plugins/sonos3/vendor/duncan3dc/sonos/src/Network.php(363): duncan3dc\Sonos\Network->getSpeakers()
#1 /var/www/nextdomdev/plugins/sonos3/core/class/sonos3.class.php(179): duncan3dc\Sonos\Network->getControllers()
#2 /var/www/nextdomdev/plugins/sonos3/core/class/sonos3.class.php(55): sonos3::syncSonos()
#3 /var/www/nextdomdev/install/restore.php(204): sonos3::restore()
#4 {main}
thrown in /var/www/nextdomdev/plugins/sonos3/vendor/duncan3dc/sonos/src/Network.php on line 265
```

Autre chose : dans la page "logs" il y a le petit "v" vers à gauche de restore, or il s'est planté et n'a pas terminé...

**Comment by slobberbone** [comment]
@Astral0 non reproduit, avec l'une de tes sauvegarde contenant le plugin en future 0.3.0. #960

**Comment by cyrilphoenix71** [comment]
on clos ?
