### ISSUE TITLE
Problème entre plugin MySensors et version NodeJS installé sur NextDom

### ISSUE THREAD

**Issue by Gis70** [NextDom/nextdom-core#969]
Le plugin MySensors ne fonctionne pas car SerialPort et Bindings ont été compilé avec des anciennes version de NodeJS.

Cf log : 
`Error: The module '/var/www/html/plugins/mySensors/resources/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/var/www/html/plugins/mySensors/resources/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/www/html/plugins/mySensors/resources/node_modules/@serialport/bindings/lib/linux.js:1:98)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
`

Pour corriger le pb il faut supprimer Serialport et Bindings et les réinstaller avec NPM.

**Comment by Gis70** [comment]
Pas reproduit en develop du 26/04, le plugin mysensor fonctionne correctement, une maj du plugin mysensors a dû corriger le pb
